services:
  - type: web
    name: dzen-backend
    runtime: node
    rootDir: backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: CLIENT_URL
        value: http://localhost:5173

  - type: web
    name: dzen-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://dzen-backend-7y56.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://dzen-backend-7y56.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
